Added VPC settings
graphile/postgraphile-lambda-example pull request #7
Opened 2019-03-20 21:44 UTC by tinymarsracing

Hi Benjie, today I implemented a proper, production suitable solution for the Lambda function to access RDS (through the VPC) while at the same time still also being able to access RDS publicly (otherwise you couldn't re-generate the Postgraphile schema from your local machine). It was a bit confusing and the AWS docs didn't always help, so I decided to add some notes on this. Also learned a lot on AWS infrastructure in the process. :-)
I felt like this still belonged to "setup" (chronologically), but feel free to move it to the bottom as an addendum or something if you prefer that.

2019-03-20 22:17 UTC, benjie requested changes
Lovely; couple minor tweaks then good to merge 👍

2019-03-20 22:17 UTC, benjie commented on README.md
> +When you're deploying Postgraphile using Lambda, you can run your DB instance on AWS as well in order to make use of AWS's integrated security using VPCs. In that case you can restrict the public acc
Remove “obviously”

2019-03-20 22:17 UTC, benjie commented on README.md
> +1. Obviously the Postgraphile Lambda function we will create needs access to the RDS instance. We achieve that by creating the Lambda function within the same VPC our RDS instance lives in.
Remove obviously

2019-03-20 22:17 UTC, benjie commented on README.md
> +```
Please add blank lines around the backtick block

2019-03-21 10:14 UTC, tinymarsracing commented
I committed again with the changes.

2019-03-21 17:37 UTC, benjie approved these changes

2019-03-21 17:37 UTC, merged

2019-03-21 17:38 UTC, benjie commented
Thanks! 🙏